// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:misik_guide/data/app_user/app_user_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'home_state.freezed.dart';

@freezed
class HomeState with _$HomeState {
  const factory HomeState({
    @Default(0) int bottomNavIndex,
    AppUser? user,
  }) = _HomeState;

  const HomeState._();

  factory HomeState.initial() => const HomeState();
}
