// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'sign_up_state.freezed.dart';

@freezed
class SignUpState with _$SignUpState {
  const factory SignUpState({
    @Default("") String email,
    @Default("") String password,
    @Default("") String confirmPassword,
    @Default("") String name,
    @Default([]) List<int> imageBytes,
  }) = _SignUpState;

  const SignUpState._();

  factory SignUpState.initial() => const SignUpState();
}
