// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'sign_in_state.freezed.dart';

@freezed
class SignInState with _$SignInState {
  const factory SignInState({
    @Default(false) bool isSignedIn,
    @Default(false) bool checkSaveEmail,
    @Default(false) bool checkAutoSignIn,
  }) = _SignInState;

  const SignInState._();

  factory SignInState.initial() => const SignInState();
}
