// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'restaurant_add_state.freezed.dart';

@freezed
class RestaurantAddState with _$RestaurantAddState {
  const factory RestaurantAddState({
    @Default("") String name,
    @Default("") String address,
    double? latitude,
    double? longitude,
    @Default([]) List<String> imagePaths,
  }) = _RestaurantAddState;

  const RestaurantAddState._();

  factory RestaurantAddState.initial() => const RestaurantAddState();
}
