// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'auth_state.freezed.dart';

@freezed
class AuthState with _$AuthState {
  const factory AuthState({
    @Default(false) bool isSignedIn,
    @Default(false) bool checkSaveEmail,
    @Default(false) bool checkAutoSignIn,
  }) = _AuthState;

  const AuthState._();

  factory AuthState.initial() => const AuthState();
}
